// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snfkhjcadljwennraudu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuZmtoamNhZGxqd2VubnJhdWR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3ODYyNjMsImV4cCI6MjA2ODM2MjI2M30.p7w49rdZ3qfkfJFrcNF1qef1PcmImU3Eo5PLezft7to";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});